# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: UI Test Pipeline

on:
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '00 14 * * *'

  workflow_dispatch:
   inputs:
    browser:
     description: 'Chose the browser to run UI tests'
     required: true
     default: 'chrome'
     type: choice
     options:
      - chrome
      - firefox
      - edge

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Install Browser
      if: ${{ github.event.inputs.browser == 'chrome' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Browser
      if: ${{ github.event.inputs.browser == 'firefox' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Install Browser
      if: ${{ github.event.inputs.browser == 'edge' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
        sudo wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -cs)/prod.list -O /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -y microsoft-edge-stable
   
    
    - name: Run UI Tests
      run: |
        echo "Running UI tests on ${{ github.event.inputs.browser }}"
        dotnet test --no-build --verbosity normal --filter Browser=${{ github.event.inputs.browser }}


    - name: Upload API test results
      uses: actions/upload-artifact@v3
      with:
        name: ui-test-results
        path: ./TestResults/
